# config/config.yaml
mysql:
  host: 
  port: 3306
  user: root
  password: 
  database: stock

api:
  edgar:
    endpoint: https://api.sec.gov/
    rate_limit: 10/60s
  yahoo:
    endpoint: https://yfapi.net/